### ISSUE TITLE
开启监听端口后CPU占用过高的解决

### ISSUE THREAD

**Issue by suimenqx** [Wangler2333/tcp_udp_web_tools-pyqt5#2]
首先感谢作者大大的优秀代码，但是我发现一些小问题。其中一个比较严重的是下面这个，在你的代码中应该有好几处用了这个，都需要修改一下。
```
        while True:
            try:
                client_socket, client_address = self.tcp_socket.accept()
            except Exception as ret:
                time.sleep(0.001)
            else:
```
类似的代码最好用time.sleep()，pass会导致cpu占用过高

**Comment by PengYunjing** [comment]
首先感谢作者大大。然后感谢SuiMengXing，@SuiMengXing：我尝试按你的改成：time.sleep(0.001)之后，发现CPU占用确实少了很多。之前CPU占用率快接近100%了，改了之后占用9%左右。

**Comment by Wangler2333** [comment]
@SuiMengXing 感谢您提出的建议，已提交新的版本：
针对非阻塞式TCP监听增加time.sleep(0.001)，降低CPU占用。
其中tcp_logic.py和web_logic.py中的非阻塞式TCP监听循环得到修改。
