### ISSUE TITLE
click_get_ip()在macOS获取ip会报错，获取不到ip。可以改进如下：

### ISSUE THREAD

**Issue by PengYunjing** [Wangler2333/tcp_udp_web_tools-pyqt5#3]
以下是修改后的click_get_ip()方法：
def click_get_ip(self):
　　"""
　　pushbutton_get_ip控件点击触发的槽
　　:return: None
　　"""
　　# 获取本机ip
　　self.lineEdit_ip_local.clear()
　　try:
　　　　s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
　　　　s.connect(('8.8.8.8', 80))
　　　　my_addr = s.getsockname()[0]
　　　　self.lineEdit_ip_local.setText(str(my_addr))
　　finally:
　　　　s.close()

**Comment by Wangler2333** [comment]
@PengYunjing 感谢您的建议，针对获取ip方法click_get_ip()已修改为如下形式：

> 

    def click_get_ip(self):
        """
        pushbutton_get_ip控件点击触发的槽
        :return: None
        """
        # 获取本机ip
        self.lineEdit_ip_local.clear()
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        try:
            s.connect(('8.8.8.8', 80))
            my_addr = s.getsockname()[0]
            self.lineEdit_ip_local.setText(str(my_addr))
        except Exception as ret:
            # 若无法连接互联网使用，会调用以下方法
            # self.signal_write_msg.emit("无法获取ip，请连接网络！\n")
            my_addr = socket.gethostbyname(socket.gethostname())
            self.lineEdit_ip_local.setText(str(my_addr))
        finally:
            s.close()

**Comment by Wangler2333** [comment]
@PengYunjing 刚刚的修改未考虑到macOS获取ip会报错这个问题，以下为最终代码：

>    
    def click_get_ip(self):
        """
        pushbutton_get_ip控件点击触发的槽
        :return: None
        """
        # 获取本机ip
        self.lineEdit_ip_local.clear()
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        try:
            s.connect(('8.8.8.8', 80))
            my_addr = s.getsockname()[0]
            self.lineEdit_ip_local.setText(str(my_addr))
        except Exception as ret:
            # 若无法连接互联网使用，会调用以下方法
            try:
                my_addr = socket.gethostbyname(socket.gethostname())
                self.lineEdit_ip_local.setText(str(my_addr))
            except Exception as ret_e:
                self.signal_write_msg.emit("无法获取ip，请连接网络！\n")
        finally:
            s.close()
