### ISSUE TITLE
请问IDE提示“Unresolved attribute reference 'connect' for class 'pyqtSignal'”是什么原因？

### ISSUE THREAD

**Issue by AncientTree** [Wangler2333/tcp_udp_web_tools-pyqt5#4]
就在`tcp_udp_web_ui.py`这一段
```Python3
    def connect(self):
        """
        控件信号-槽的设置
        :param : QDialog类创建的对象
        :return: None
        """
        self.signal_write_msg.connect(self.write_msg)
        self.comboBox_tcp.currentIndexChanged.connect(self.combobox_change)
```
中的倒数第二句
```python3
        self.signal_write_msg.connect(self.write_msg)
```
Pycharm提示`Unresolved attribute reference 'connect' for class 'pyqtSignal'`
我看你用的确实是PyQt5啊，版本是一样的。

**Comment by Wangler2333** [comment]
![image](https://user-images.githubusercontent.com/25179036/43311086-fee18abc-91bb-11e8-88fe-1cb66aadf4d3.png)
是否为这种形式的提示？

如果是这种形式的提示
可忽略，直接运行

这是因为IDE无法在类中找到'connect'方法，实际运行中是存在这个方法的

**Comment by AncientTree** [comment]
确实是你说的这种形式，谢谢啦
